IF NOT EXISTS (SELECT 1 FROM dbo.Governorates)
BEGIN
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Alexandria',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Assiut',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Aswan',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Beheira',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Bani Suef',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Cairo',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Daqahliya',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Damietta',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Fayyoum',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Gharbiya',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Giza',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Ismailia',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Kafr El Sheikh',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Luxor',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Marsa Matrouh',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Minya',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Monofiya',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('New Valley',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('North Sinai',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Port Said',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Qalioubiya',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Qena',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Red Sea',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Sharqiya',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Sohag',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('South Sinai',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())
INSERT INTO dbo.Governorates(Name, IsDeleted, CreatedById, CreatedOn) VALUES ('Suez',0,(select Id from dbo.AspNetUsers where UserName = 'admin'), GETDATE())	
END
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM dbo.Areas)
BEGIN
INSERT INTO [dbo].[Areas] ([Name],[GovernorateId],[IsDeleted],[CreatedById],[CreatedOn]) VALUES('Maadi',6,0,(select Id from dbo.AspNetUsers where UserName = 'admin'),GETDATE())
INSERT INTO [dbo].[Areas] ([Name],[GovernorateId],[IsDeleted],[CreatedById],[CreatedOn]) VALUES('Garden City',6,0,(select Id from dbo.AspNetUsers where UserName = 'admin'),GETDATE())
INSERT INTO [dbo].[Areas] ([Name],[GovernorateId],[IsDeleted],[CreatedById],[CreatedOn]) VALUES('Doki',11,0,(select Id from dbo.AspNetUsers where UserName = 'admin'),GETDATE())
INSERT INTO [dbo].[Areas] ([Name],[GovernorateId],[IsDeleted],[CreatedById],[CreatedOn]) VALUES('6 October',11,0,(select Id from dbo.AspNetUsers where UserName = 'admin'),GETDATE())
INSERT INTO [dbo].[Areas] ([Name],[GovernorateId],[IsDeleted],[CreatedById],[CreatedOn]) VALUES('Miami',1,0,(select Id from dbo.AspNetUsers where UserName = 'admin'),GETDATE())
INSERT INTO [dbo].[Areas] ([Name],[GovernorateId],[IsDeleted],[CreatedById],[CreatedOn]) VALUES('Anfoshi',1,0,(select Id from dbo.AspNetUsers where UserName = 'admin'),GETDATE())
INSERT INTO [dbo].[Areas] ([Name],[GovernorateId],[IsDeleted],[CreatedById],[CreatedOn]) VALUES('Ras Elbar',8,0,(select Id from dbo.AspNetUsers where UserName = 'admin'),GETDATE())
INSERT INTO [dbo].[Areas] ([Name],[GovernorateId],[IsDeleted],[CreatedById],[CreatedOn]) VALUES('New Damietta',8,0,(select Id from dbo.AspNetUsers where UserName = 'admin'),GETDATE())
END